spring.application.name=api-gateway
server.port=${PORT}
spring.servlet.multipart.enabled=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.http.clients.imperative.factory=http-components

gateway.env.allowed-origins=${ALLOWED_ORIGINS}
gateway.env.core-service-url=${CORE_SERVICE_URL}
gateway.env.document-service-url=${DOCUMENT_SERVICE_URL}
gateway.env.ia-service-url=${IA_SERVICE_URL}